### PR TITLE
random matrix

### PR DESCRIPTION
**Pull request by hrudai2002**
- random_matrix(row, col, low, high) - returns a matrix 
   - `row` rows
   - `col` columns 
   - values in the matrix in the range `[low, high]`

### CODE REVIEW

**Comment by hrudai2002** [comment]
@Omar622 can you please look into this pr. If there are any changes please let me know 🙂

**Comment by Omar622** [comment]
First thank you for your effort and PR.

There's few things in code:
1. I think you included `ctime` accidentally in `random_generator_lib.h` so please remove it.
2. In README, function docs, return data type is not clear it should be like `vector<vector<long long>>`
3. In the function source code there's an overflow since `random64` return `long long` while matrix is `int` I think you should use `long long` instead of `int`.

**Comment by hrudai2002** [comment]
Yeah will look into it

**Comment by hrudai2002** [comment]
@Omar622 yeah done with the comments .. 👍

**Comment by Omar622** [comment]
`low`, `high` data types will be `long long` too. (in function implementation)

**Comment by hrudai2002** [comment]
@Omar622 Yeah done .. 👍

**Pull request merged**
